server:
  port: 8082

logging:
  level:
    root: WARN
    travel.z: INFO
    org.springframework.web: INFO
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %5p -- [%t] %-40.40logger{39} : %m%n%xEx{10}'
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %5p -- [%t] %-40.40logger{39} : %m%n%xEx{10}'

db:
    #mysql:
        #user: qianhu
        #password: Lasjdf99327adfaf@#weo
        #connection: jdbc:mysql://rm-bp1g4mqphj9u2kdc9.mysql.rds.aliyuncs.com:3306/qianhu?characterEncoding=UTF8
        #driverClassName: com.mysql.jdbc.Driver
    mongodb:
        connection: "mongodb://localhost/admin"
    utils: none
    
spring:
    datasource:
        url: jdbc:mysql://rm-bp1g4mqphj9u2kdc9.mysql.rds.aliyuncs.com:3306/test?characterEncoding=UTF8
        username: qianhu
        password: 
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        
 
     
        